truncate table class cascade;

alter sequence class_no_seq restart 6; 
alter sequence lesson_no_seq restart 6; 
alter sequence student_no_seq restart 1; 
alter sequence teacher_no_seq restart 2; 
alter sequence test_no_seq restart 1;
alter sequence teststudent_no_seq restart 1; 


insert into class values( 1, '6I' );
insert into class values( 2, '6K' ); 
insert into class values( 3, '6P' ); 
insert into class values( 4, '7A' ); 
insert into class values( 5, '7B' ); 

insert into teacher values( 1, 'Özge KONAR' ); 

insert into lesson values( 1, '6I Türkçe Dersi', 1, 1 ); 
insert into lesson values( 2, '6K Türkçe Dersi', 2, 1 ); 
insert into lesson values( 3, '6P Türkçe Dersi', 3, 1 ); 
insert into lesson values( 4, '7A Türkçe Dersi', 4, 1 ); 
insert into lesson values( 5, '7B Türkçe Dersi', 5, 1 ); 

insert into student values( 

insert into student values( 1, 'female', 'Burçin ÇETİN', 4, 1 );
insert into student values( 2, 'male', 'Kaan ÇOŞKUN', 523, 1 );
insert into student values( 3, 'female', 'Başak ERGÜDER', 824, 1 );
insert into student values( 4, 'male', 'Sezen BÜR', 825, 1 );
insert into student values( 5, 'female', 'Eda ALTAY', 848, 1 );
insert into student values( 6, 'male', 'Umut MERT', 850, 1 );
insert into student values( 7, 'female', 'Edanur ÇALIŞKAN', 1024, 1 );
insert into student values( 8, 'male', 'Muhammed OLGUN', 1045, 1 );
insert into student values( 9, 'male', 'Dursun Ali ÇELİK', 1175, 1 );
insert into student values( 10, 'female', 'Birsu Hilal İMECİ', 1176, 1 );
insert into student values( 11, 'male', 'Rafet GÜCÜKKILINÇ', 1177, 1 );
insert into student values( 12, 'male', 'Mustafa DURMUŞ', 1192, 1 );
insert into student values( 13, 'male', 'Yiğit Efe YILDIZ', 1193, 1 );
insert into student values( 14, 'female', 'Esra EDABALİ', 1531, 1 );
insert into student values( 15, 'female', 'Sude Nur ÇOŞKUN', 1532, 1 );
insert into student values( 16, 'male', 'Soner KARTAL', 1533, 1 );
insert into student values( 17, 'male', 'Deniz YILDIRIM', 1544, 1 );
insert into student values( 18, 'female', 'Gülüstan KARADUMAN', 1882, 1 );
insert into student values( 19, 'female', 'Simanur ŞAHİN', 1883, 1 );
insert into student values( 20, 'female', 'Nida Nur İNCİ', 1886, 1 );
insert into student values( 21, 'female', 'Pelin Su ÇAKIR', 1895, 1 );
insert into student values( 22, 'female', 'Kübra İrem BAYCAN', 1896, 1 );
insert into student values( 23, 'female', 'Onay YILĞIN', 1905, 1 );
insert into student values( 24, 'female', 'Doğa YAMAN', 1925, 1 );
insert into student values( 25, 'male', 'Fırat KAYA', 1952, 1 );
insert into student values( 26, 'female', 'Asiye Özlem SÜMER', 1955, 1 );
insert into student values( 27, 'male', 'Emre ESENLİKCİ', 2111, 1 );
insert into student values( 28, 'male', 'Doğukan Ali VURAL', 2202, 1 );
insert into student values( 29, 'male', 'Görkem YEŞİLYURT', 2207, 1 );
insert into student values( 30, 'female', 'Beyzanur BORAN', 2208, 1 );
insert into student values( 31, 'female', 'Derya DEMİR', 2211, 1 );
insert into student values( 32, 'male', 'Görkem KARADEMİR', 2221, 1 );
insert into student values( 33, 'female', 'Zerda DEMİRTÜRK', 3047, 1 );
insert into student values( 34, 'male', 'Cenker UYSAL', 3075, 1 );
insert into student values( 35, 'female', 'Eda ÇANKAYA', 3742, 1 );
insert into student values( 36, 'male', 'İsmail Mert SÖĞÜT', 3875, 1 );
insert into student values( 60, 'male', 'Emirhan ERGÜN', 82, 2 );
insert into student values( 61, 'male', 'Uğur ÖZSOY', 778, 2 );
insert into student values( 62, 'female', 'Elif KELEŞ', 1181, 2 );
insert into student values( 63, 'male', 'Yiğit BAYRAK', 1184, 2 );
insert into student values( 64, 'female', 'Ceren SEVİNÇ', 1191, 2 );
insert into student values( 65, 'female', 'Nazlıcan ASAV', 1543, 2 );
insert into student values( 66, 'female', 'Tuğçe SARI', 1546, 2 );
insert into student values( 67, 'male', 'Kerem İRFANOĞLU', 1547, 2 );
insert into student values( 68, 'male', 'Emre TAŞDAN', 1549, 2 );
insert into student values( 69, 'male', 'Yunus TAŞDAN', 1550, 2 );
insert into student values( 70, 'male', 'Barış GÜMÜŞ', 1554, 2 );
insert into student values( 71, 'female', 'Duygu KURT', 1556, 2 );
insert into student values( 72, 'female', 'Seçil ÇİL', 1558, 2 );
insert into student values( 73, 'male', 'Tayfun DELİBAŞ', 1565, 2 );
insert into student values( 74, 'male', 'Doğukan AYDEMİŞ', 1574, 2 );
insert into student values( 75, 'male', 'Adem AGSAR', 1577, 2 );
insert into student values( 76, 'male', 'Egemen ŞAHİN', 1582, 2 );
insert into student values( 77, 'female', 'Fadime Hanım PAMUKCU', 1617, 2 );
insert into student values( 78, 'female', 'Ayşe irem ŞENER', 1889, 2 );
insert into student values( 79, 'female', 'Sümeyye GENÇDAL', 1897, 2 );
insert into student values( 80, 'female', 'Simge KAYA', 1900, 2 );
insert into student values( 81, 'male', 'Mehmet KAYA', 1902, 2 );
insert into student values( 82, 'male', 'Burak KILIÇ', 1903, 2 );
insert into student values( 83, 'male', 'Tolga DAĞ', 1904, 2 );
insert into student values( 84, 'female', 'Sıla BAYSUNGUR', 1908, 2 );
insert into student values( 85, 'female', 'Gülçin KAZAN', 2205, 2 );
insert into student values( 86, 'male', 'Batuhan ÇİZMAZ', 2206, 2 );
insert into student values( 87, 'male', 'Mert AKINCI', 2209, 2 );
insert into student values( 88, 'female', 'Senay BAYSAL', 2217, 2 );
insert into student values( 89, 'male', 'Tuna ATSIZ', 2219, 2 );
insert into student values( 90, 'female', 'Deniz ÖZLÜ', 2220, 2 );
insert into student values( 91, 'female', 'Sedef Nur DİRİL', 2231, 2 );
insert into student values( 92, 'female', 'İpek RUŞAN', 2234, 2 );
insert into student values( 93, 'female', 'Yaren GÖRAL', 3056, 2 );
insert into student values( 94, 'male', 'Erdal Eren GÖRAL', 3057, 2 );
insert into student values( 95, 'male', 'Berk Çağatay ŞENYAŞA', 3796, 2 );
insert into student values( 96, 'female', 'Zelal TAŞER', 3846, 2 );
insert into student values( 97, 'female', 'Gülçin BATI', 3890, 2 );
insert into student values( 98, 'male', 'Salih Yiğit ÇELİK', 3944, 2 );
insert into student values( 99, 'male', 'Furkan ÇALIŞ', 70, 3 );
insert into student values( 100, 'male', 'Yusuf Kerem KABAHOR', 135, 3 );
insert into student values( 101, 'female', 'Öykü Naz DAŞ', 1053, 3 );
insert into student values( 102, 'male', 'Kemal Can ULUSU', 1615, 3 );
insert into student values( 103, 'male', 'Sarp Ali CANPULUT', 1621, 3 );
insert into student values( 104, 'male', 'Ulaş KARAKAŞ', 1888, 3 );
insert into student values( 105, 'male', 'Koray KARATAŞ', 2183, 3 );
insert into student values( 106, 'male', 'Berkay ALTINAY', 2264, 3 );
insert into student values( 107, 'male', 'Muhammet BAYRAK', 2297, 3 );
insert into student values( 108, 'male', 'Sedat ABAY', 2317, 3 );
insert into student values( 109, 'male', 'Atalay CAN', 3060, 3 );
insert into student values( 110, 'male', 'Eren ÇELİK', 3077, 3 );
insert into student values( 111, 'female', 'Habibe KAYA', 3099, 3 );
insert into student values( 112, 'female', 'Fatma ÇALBAY', 3100, 3 );
insert into student values( 113, 'female', 'Nuray MERT', 3128, 3 );
insert into student values( 114, 'male', 'Alişan ALİŞANOĞLU', 3130, 3 );
insert into student values( 115, 'female', 'Buse AYDIN', 3133, 3 );
insert into student values( 116, 'female', 'Özüm Hilal ÇAVUŞ', 3137, 3 );
insert into student values( 117, 'female', 'Sema GÖK', 3140, 3 );
insert into student values( 119, 'male', 'Berkecan ADIGÜZEL', 3384, 3 );
insert into student values( 120, 'male', 'Anıl Furkan POLAT', 3708, 3 );
insert into student values( 121, 'female', 'Aslı YILDIZ', 3713, 3 );
insert into student values( 122, 'female', 'Esma Sude AYDIN', 3757, 3 );
insert into student values( 123, 'female', 'Semra BULCUM', 3767, 3 );
insert into student values( 124, 'male', 'Şahan ÖTER', 3777, 3 );
insert into student values( 125, 'female', 'Tuğbanur ÇELEBİ', 3782, 3 );
insert into student values( 126, 'male', 'Yusufcan POLAT', 3850, 3 );
insert into student values( 127, 'male', 'Kaan Mert SARIDERE', 3874, 3 );
insert into student values( 128, 'female', 'İrem Beyza AKSOY', 3878, 3 );
insert into student values( 129, 'male', 'Hüseyin Emre SÖĞÜT', 3883, 3 );
insert into student values( 130, 'female', 'Gül Deniz GÜLMEZ', 3891, 3 );
insert into student values( 131, 'male', 'Muhammet ÇİLGİN', 3919, 3 );
insert into student values( 132, 'female', 'Müzeyyen Sude YENİSOY', 3927, 3 );
insert into student values( 133, 'female', 'Selin Naz ANLI', 3948, 3 );
insert into student values( 134, 'female', 'Hatun KAYA', 6053, 3 );
insert into student values( 136, 'male', 'Ümit ERDEN', 9, 4 );
insert into student values( 137, 'male', 'Tarık ÇELİKTEN', 11, 4 );
insert into student values( 138, 'male', 'Yusufcan ŞANLI', 21, 4 );
insert into student values( 139, 'male', 'Berke EROL', 42, 4 );
insert into student values( 140, 'female', 'Nazlıcan YANAR', 110, 4 );
insert into student values( 141, 'male', 'Ozan AKKOŞ', 116, 4 );
insert into student values( 142, 'female', 'Pelin ANIL', 118, 4 );
insert into student values( 143, 'female', 'Pelin TOPCUOĞLU', 119, 4 );
insert into student values( 144, 'male', 'Ahmet YILDIRIM', 158, 4 );
insert into student values( 145, 'male', 'Kaan AKKÖK', 199, 4 );
insert into student values( 146, 'male', 'Ali ALKAN', 231, 4 );
insert into student values( 147, 'male', 'Barış KURT', 259, 4 );
insert into student values( 148, 'female', 'Mine MENEGŞE', 262, 4 );
insert into student values( 149, 'male', 'Sezer KANTEKİN', 281, 4 );
insert into student values( 150, 'male', 'Resul ERDOĞAN', 313, 4 );
insert into student values( 151, 'male', 'Alper ALTAY', 384, 4 );
insert into student values( 152, 'male', 'Sinan DURĞUN', 430, 4 );
insert into student values( 153, 'female', 'Gizem PAKKAN', 487, 4 );
insert into student values( 154, 'male', 'Enes YILDIZ', 601, 4 );
insert into student values( 155, 'male', 'Kaan Berk AYDIN', 602, 4 );
insert into student values( 156, 'male', 'Bahtiyar GÖKTAŞ', 608, 4 );
insert into student values( 157, 'male', 'Oğuzcan BIÇAKCI', 615, 4 );
insert into student values( 158, 'male', 'Yunus Emre KANATCI', 672, 4 );
insert into student values( 159, 'female', 'Helin GÜL', 695, 4 );
insert into student values( 160, 'female', 'Cemile Nur KOYUNCU', 705, 4 );
insert into student values( 161, 'female', 'Melike ERASLAN', 710, 4 );
insert into student values( 162, 'female', 'İrem ASLAN', 734, 4 );
insert into student values( 163, 'female', 'Melodi KOÇ', 736, 4 );
insert into student values( 164, 'female', 'Aslı YILMAZ', 790, 4 );
insert into student values( 165, 'female', 'Özge AKYILDIZ', 796, 4 );
insert into student values( 166, 'female', 'Emine Mihriban YILMAZ', 854, 4 );
insert into student values( 167, 'male', 'Emircan ALTÜRK', 865, 4 );
insert into student values( 168, 'female', 'Fatma ÇELEBİ', 1422, 4 );
insert into student values( 169, 'male', 'Emrullah ESİN', 5400, 4 );
insert into student values( 170, 'male', 'Ferhatcan ÇELEBİ', 7001, 4 );
insert into student values( 171, 'male', 'Ali AKTAŞ', 7050, 4 );
insert into student values( 172, 'male', 'Abdullah Şenol ÖĞÜTÇÜ', 7058, 4 );
insert into student values( 173, 'female', 'Sıla ÖZÇEKEN', 8086, 4 );
insert into student values( 174, 'male', 'Naim ATEŞ', 9014, 4 );
insert into student values( 175, 'female', 'Gizem Melisa ÇETİN', 9027, 4 );
insert into student values( 176, 'female', 'Canan SOYLU', 9030, 4 );
insert into student values( 177, 'female', 'Öykü Sibel DOĞAN', 29, 5 );
insert into student values( 178, 'male', 'Cem Vural YILMAZ', 37, 5 );
insert into student values( 179, 'male', 'Berk ADIBEKE', 38, 5 );
insert into student values( 180, 'female', 'Aylin AKGÜL', 40, 5 );
insert into student values( 181, 'female', 'Zehra KÜPŞİ', 126, 5 );
insert into student values( 182, 'male', 'Emir KARADERE', 443, 5 );
insert into student values( 183, 'female', 'Elif Yağmur YILAN', 516, 5 );
insert into student values( 184, 'male', 'Hüseyin ACAR', 522, 5 );
insert into student values( 185, 'female', 'Melek GÜNEŞ', 536, 5 );
insert into student values( 186, 'female', 'Dilhan SAVAŞ', 546, 5 );
insert into student values( 187, 'female', 'Zeynep ÇİMEN', 590, 5 );
insert into student values( 188, 'male', 'Mertcan ÇİÇEK', 598, 5 );
insert into student values( 189, 'male', 'Taylan Özgür YÜKSEL', 645, 5 );
insert into student values( 190, 'male', 'Sefa ECER', 682, 5 );
insert into student values( 191, 'female', 'Yaren ULUCAN', 712, 5 );
insert into student values( 192, 'female', 'Sude ŞİMŞİR', 714, 5 );
insert into student values( 193, 'male', 'Doğukan GÜDER', 716, 5 );
insert into student values( 194, 'female', 'Hazal ULUCAN', 725, 5 );
insert into student values( 195, 'female', 'Rozerin Ceyda YEŞİLTAŞ', 728, 5 );
insert into student values( 196, 'male', 'Barış MERT', 738, 5 );
insert into student values( 197, 'male', 'Furkan ÇAMOĞLU', 746, 5 );
insert into student values( 198, 'female', 'Fatmagül AYVACIOĞLU', 755, 5 );
insert into student values( 199, 'female', 'Gözde ARSLAN', 765, 5 );
insert into student values( 200, 'male', 'Fırat GÜNDOĞDU', 770, 5 );
insert into student values( 201, 'male', 'Murat PELİT', 795, 5 );
insert into student values( 202, 'female', 'Pınar ÖZÇAKTU', 804, 5 );
insert into student values( 203, 'male', 'Muhammet Musfata AKGÜL', 810, 5 );
insert into student values( 204, 'male', 'Çağatay KARTAL', 815, 5 );
insert into student values( 205, 'female', 'Rabia ÖZKAN', 816, 5 );
insert into student values( 206, 'male', 'Selimcan ÖZTÜRK', 926, 5 );
insert into student values( 207, 'male', 'Ceyhan CENGİZ', 1074, 5 );
insert into student values( 208, 'female', 'Melisa BABACAN', 1087, 5 );
insert into student values( 209, 'male', 'Ali ÇELEBİ', 1145, 5 );
insert into student values( 210, 'male', 'Barış IŞIK', 1146, 5 );
insert into student values( 211, 'male', 'Hasan Mert ADEKA', 1350, 5 );
insert into student values( 212, 'female', 'Damla DEMİR', 1717, 5 );
insert into student values( 213, 'male', 'Caner DEMİR', 1759, 5 );
insert into student values( 214, 'male', 'Serhat ÇAKAR', 1827, 5 );
insert into student values( 215, 'female', 'Fatma ERYILMAZ', 9017, 5 );
insert into student values( 216, 'male', 'Mehmet Salih ERYILMAZ', 9021, 5 );
insert into student values( 217, 'female', 'Aylin ÇAKİN', 9043, 5 );
