//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.12 at 10:09:37 PM EET
//

package ilkerkonar.com.products.product_query_web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="personType" type="{http://com.ilkerkonar/products/product-query-web-service}PersonType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {
	"productType",
	"username",
	"personType"
} )
@XmlRootElement( name = "getProductsRequest" )
public class GetProductsRequest {

	protected int			productType;
	@XmlElement( required = true, nillable = false )
	protected String		username;
	@XmlElement( required = true )
	protected PersonType	personType;

	/**
	 * Gets the value of the productType property.
	 * 
	 */
	public int getProductType() {
		return productType;
	}

	/**
	 * Sets the value of the productType property.
	 * 
	 */
	public void setProductType( final int value ) {
		productType = value;
	}

	/**
	 * Gets the value of the username property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * Sets the value of the username property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setUsername( final String value ) {
		username = value;
	}

	/**
	 * Gets the value of the personType property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link PersonType }
	 *     
	 */
	public PersonType getPersonType() {
		return personType;
	}

	/**
	 * Sets the value of the personType property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link PersonType }
	 *     
	 */
	public void setPersonType( final PersonType value ) {
		personType = value;
	}

}
