//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 09:34:04 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.ilkerkonar/products/product-query-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ilkerkonar.com.products.product_query_web_service;
